# Generated by Django 3.2.18 on 2023-05-26 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperienceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('skills', models.ManyToManyField(to='resumee.Skill')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumee.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='Resumee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('website', models.URLField(blank=True, max_length=255)),
                ('github_link', models.URLField(max_length=255)),
                ('linkedin_link', models.URLField(max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='resumee')),
                ('objective', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('education_history', models.ManyToManyField(to='resumee.Education')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumee.template')),
                ('work_history', models.ManyToManyField(to='resumee.WorkExperience')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=30)),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumee.education')),
                ('work_experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumee.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('foreign', models.BooleanField(default=False)),
                ('country', models.CharField(max_length=200)),
                ('resumes', models.ManyToManyField(to='resumee.Resumee')),
            ],
        ),
    ]
