# Generated by Django 3.2.18 on 2023-05-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='work_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], default='Full Time', max_length=30),
        ),
    ]
