# Generated by Django 3.2.18 on 2023-05-26 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0002_workexperience_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumee',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumee.template'),
        ),
    ]
