# Generated by Django 3.2.18 on 2023-05-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0003_alter_resumee_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiencedescription',
            name='skills',
            field=models.ManyToManyField(blank=True, to='resumee.Skill'),
        ),
    ]
