# Generated by Django 3.2.18 on 2023-05-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0004_alter_workexperiencedescription_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumee',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resumee',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
