# Generated by Django 3.2.18 on 2023-05-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0005_auto_20230527_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='degree',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
