# Generated by Django 3.2.18 on 2023-05-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0006_skill_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('Conversational', 'Conversational')], default='Conversational', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField()),
                ('description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='resumee',
            name='languages',
            field=models.ManyToManyField(blank=True, to='resumee.Language'),
        ),
        migrations.AddField(
            model_name='resumee',
            name='portfolios',
            field=models.ManyToManyField(blank=True, to='resumee.Portfolio'),
        ),
    ]
