# Generated by Django 3.2.18 on 2023-06-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0007_auto_20230531_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
