# Generated by Django 3.2.18 on 2023-06-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0009_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumee',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
