# Generated by Django 3.2.18 on 2023-06-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0010_resumee_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumee',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
