# Generated by Django 3.2.18 on 2023-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumee', '0011_resumee_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumee',
            name='roles',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
